# Generated by Django 5.0.4 on 2024-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_title', models.CharField(max_length=100)),
                ('events_description', models.TextField()),
                ('events_date', models.DateField()),
                ('events_time', models.TimeField()),
                ('events_organizer_details', models.TextField()),
                ('events_location', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
